### ISSUE TITLE
Provide user feedback when ArchivesSpace resource fetch is underway

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/cartographer_frontend#54]
When a user clicks the "Fetch from ArchivesSpace" button in the Arrangement Map Component detail modal (or presses enter in that modal) it is not immediately obvious that the system is doing anything. Given that fetching data from ArchivesSpace is not immediate, some visual cues need to be presented which indicate that the system is responding to user input and is fetching data. 

A couple of ideas (@HaSistrunk would love to have your feedback on which of these seem best or if you have other ideas):
- Change button text to "Fetching data.." and disable button (or something similar).
- Replace input with a loading GIF or text.

**Comment by HaSistrunk** [comment]
Good call. I think since the fetch time isn't usually super long, we should stay away from anything too animated since it may be jarring to have it there for a short time and then disappear. What about using the[ Bootstrap spinner ](https://getbootstrap.com/docs/4.4/components/spinners/#buttons) in the button, and change the button text to "Fetching..." as you suggested?
